### ISSUE TITLE
Cards Page

### ISSUE THREAD

**Issue by Yogeshlodhi** [mohit200008/medi-Care#111]
### What happened?

The Doctors card are not aligned in a good style. The cards can be given some better look and positions on the page to give it a better UI

### How can we reproduce this bug?

No

### Urgency (Optional)

Medium priority

**Comment by mohit200008** [comment]
Yes go ahead, just make sure colour scheme doesn't mismatch

**Comment by Yogeshlodhi** [comment]
@mohit200008 Kindly add Codepeak label for this issue and award me points for raising issue

**Comment by saurabhbakolia** [comment]
![image](https://user-images.githubusercontent.com/78996216/207050501-ac430bc7-f37c-4714-a356-e70f05650e7a.png)

Hi, @mohit200008  can you explain a little bit about this issue. I  am not getting exactly how you want to align doctors card. If this issue is not assigned yet. I would like to work on this issue. 

@KWOC

**Comment by mohit200008** [comment]
It needs to be a vertical box with doctors photo as a cover and below is the content it's showing

**Comment by Yogeshlodhi** [comment]
@mohit200008 Kindly award me points for raising the issue

**Comment by mohit200008** [comment]
Will add the tags and the points will be automatically updated

**Comment by saurabhbakolia** [comment]
So, you want me to add some random image and check for the same right?

**Comment by saurabhbakolia** [comment]
@kwoc

**Comment by saurabhbakolia** [comment]
This issue is resolved.
